name: CD - Deploy Backend Services to AKS

on:
  workflow_dispatch:
    inputs:
      aks_cluster_name:
        description: 'Name of the AKS Cluster to deploy to'
        required: true
        default: 'week08aks'
      aks_resource_group:
        description: 'Resource Group of the AKS Cluster'
        required: true
        default: 'week08rg'
      aks_acr_name:
        description: 'Name of ACR'
        required: true
        default: 'week08acr'

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    environment: Production
    
    outputs:
      PRODUCT_API_IP: ${{ steps.get_product_ip.outputs.external_ip }}
      ORDER_API_IP: ${{ steps.get_order_ip.outputs.external_ip }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Set Kubernetes context (get AKS credentials)
        run: |
          az aks get-credentials --resource-group ${{ github.event.inputs.aks_resource_group }} --name ${{ github.event.inputs.aks_cluster_name }} --overwrite-existing

      - name: Grant AcrPull to AKS kubelet identity (policy-safe)
        run: |
         set -e
         ACR_ID=$(az acr show -n ${{ inputs.aks_acr_name }} --query id -o tsv)

         # Try Managed Identity (most AKS clusters)
         KUBE_OID=$(az aks show \
          -g ${{ inputs.aks_resource_group }} \
          -n ${{ inputs.aks_cluster_name }} \
          --query "identityProfile.kubeletidentity.objectId" -o tsv 2>/dev/null || true)

         if [ -n "$KUBE_OID" ] && [ "$KUBE_OID" != "null" ]; then
          echo "Granting AcrPull to kubelet identity: $KUBE_OID"
          az role assignment create --assignee-object-id "$KUBE_OID" --role AcrPull --scope "$ACR_ID"
         else
          # Fallback: legacy SP-based cluster
          SP_APPID=$(az aks show \
           -g ${{ inputs.aks_resource_group }} \
           -n ${{ inputs.aks_cluster_name }} \
           --query "servicePrincipalProfile.clientId" -o tsv)
          echo "Granting AcrPull to cluster SP: $SP_APPID"
          az role assignment create --assignee "$SP_APPID" --role AcrPull --scope "$ACR_ID"
         fi
          
      - name: Deploy Backend Infrastructure (Namespace, ConfigMaps, Secrets, Databases)
        run: |
          echo "Deploying backend infrastructure..."
          cd k8s/
          kubectl apply -f configmaps.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f product-db.yaml
          kubectl apply -f order-db.yaml

          echo "PRODUCT_DB_SERVICE=product-db-service-w08e1" >> $GITHUB_ENV
          echo "ORDER_DB_SERVICE=order-db-service-w08e1"     >> $GITHUB_ENV

      - name: Deploy Backend Microservices (Product, Order)
        run: |
          set -e
          # apply one by one (make sure these files exist)
          kubectl apply -n $BACKEND_NS -f k8s/product-service.yaml
          kubectl apply -n $BACKEND_NS -f k8s/order-service.yaml

      - name: List services in namespace (verify)
        run: kubectl -n $BACKEND_NS get svc
      
      - name: Wait for Backend LoadBalancer IPs
        run: |
          id: wait_ips
          run: |
           set -e
           echo "Waiting for Product, Order LoadBalancer IPs to be assigned (up to 5 minutes)..."
           for i in {1..60}; do
            PRODUCT_IP=$(kubectl -n $BACKEND_NS get svc product-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
            ORDER_IP=$(kubectl  -n $BACKEND_NS get svc order-service  -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
            if [ -n "$PRODUCT_IP" ] && [ -n "$ORDER_IP" ]; then
             echo "product_ip=$PRODUCT_IP" >> $GITHUB_OUTPUT
             echo "order_ip=$ORDER_IP"     >> $GITHUB_OUTPUT
             exit 0
            fi
            echo "Attempt $i/60 to get IPs..."
            sleep 5
          done
          echo "Timed out waiting for LoadBalancer IPs"
          exit 1
          
      - name: Capture Product Service IP for Workflow Output
        id: get_product_ip
        run: echo "external_ip=${{ env.PRODUCT_IP }}" >> $GITHUB_OUTPUT
      
      - name: Capture Order Service IP for Workflow Output
        id: get_order_ip
        run: echo "external_ip=${{ env.ORDER_IP }}" >> $GITHUB_OUTPUT

      - name: Logout from Azure
        run: az logout
