# week08/.github/workflows/frontend-cd.yml
name: CD - Deploy Frontend to AKS

on:
  workflow_dispatch:
    inputs:
      product_api_ip:
        description: 'External IP of Product Service (e.g., http://X.X.X.X:8000)'
        required: true
        default: 'http://<ip_address>:8000'
      order_api_ip:
        description: 'External IP of Order Service (e.g., http://Y.Y.Y.Y:8001)'
        required: true
        default: 'http://<ip_address>:8001'
      aks_cluster_name:
        description: 'Name of the AKS Cluster to deploy to'
        required: true
        default: 'week08aks'
      aks_resource_group:
        description: 'Resource Group of the AKS Cluster'
        required: true
        default: 'week08rg'
      acr_name:
        description: 'Azure Container Registry NAME (no .azurecr.io)'
        required: true
        default: 'week08acr'

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production
    env:
      ACR_NAME: ${{ github.event.inputs.acr_name }}
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses:
