name: Frontend CI - Build & Push Image

on:
  # Run on demand
  workflow_dispatch:
    inputs:
      acr_name:
        description: 'Azure Container Registry NAME (no .azurecr.io)'
        required: true
        default: 'week08acr'
  # And on code changes to the frontend
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      # For manual runs this comes from the input.
      # For push runs, CHANGE this default to your real ACR name.
      ACR_NAME: ${{ github.event.inputs.acr_name || 'week08acr' }}
      IMAGE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate ACR name
        run: |
          if [ -z "${ACR_NAME}" ]; then
            echo "ERROR: ACR_NAME is empty. Set the workflow input 'acr_name' or hardcode the env."
            exit 1
          fi
          echo "ACR_NAME=${ACR_NAME}"

      - name: Resolve ACR login server
        run: echo "LOGIN_SERVER=$(az acr show -n "$ACR_NAME" --query loginServer -o tsv)" >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        run: az acr login --name "$ACR_NAME"

      - name: Build & Push image
        run: |
          docker build -t "$LOGIN_SERVER/frontend:$IMAGE_TAG" ./frontend
          docker push  "$LOGIN_SERVER/frontend:$IMAGE_TAG"

      - name: Azure Logout
        run: az logout
